### ISSUE TITLE
Fur Elise 1 note error

### ISSUE THREAD

**Issue by gergepalfi** [rubytupallo/3MeloD#4]
There is an error at the very beginning of the melody

E5
Ds5
E5
Ds5
E5
B4
**D5** not D4
**C5**  not C4
A4
A4

**Comment by Spencers-Desk** [comment]
This has been fixed, but not in this repository. News to follow in the coming week or two!

**Comment by Spencers-Desk** [comment]
This has been fixed, just not in this repository! News to come
